Currency: GP
Language: ja_JP
#Supported language list: ja_JP, en_US
Translate_Folder: translate
Initial_Holdings: 100000
Use_Vault: true

#BSBank Service
Yml_Folder: yml
Decimal_Balance: false
Singular_Integer_Currency: #dollar
Plural_Integer_Currency: #dollars
Singular_Decimal_Currency: #scent
Plural_Decimal_Currency: #scents
Allow_Debt: true
Debt_Limit: 100000
Allow_Multiple_Account: false
Bank_Account_Limit: 2

Login_Item:
#Item_Type is Item, Money
  1_Item:
    Item_Type: Money
    Money: 10000