name: BSEconomy
version: '${project.version}'
main: com.github.beadieststar64.plugins.bsseries.bseconomy.BSEconomy
api-version: '1.20'
depend: [BSCore, Vault]
loadbefore: [Vault]

commands:
  bank:
    permission: op